Feature/waypoint update unobs lc
usdot-fhwa-stol/carma-platform pull request #1042
Opened 2021-01-20 22:31 UTC by adev4a

# PR Details
Add waypoint generation methodology to unobstructed lanechange.

## Description
Update the Lane Change Tactical Plugin to behave in a compatible manner with the new Guidance waypoint generation methodology. The Lane Change Plugin should get the geometric and speed basis for it's trajectory plan from the HD vector map data, similar to In-lane Cruising Plugin.

Added waypoint generation methodology using Bspline for interpolation.
## Related Issue

## Motivation and Context

## How Has This Been Tested?
Unit Tested

The GuidanceWM test lib was used to create a vector map, a lane change route was specified and a trajectory generated. 

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-01-28 22:18 UTC, kjrush requested changes

2021-02-02 15:26 UTC, adev4a commented on .sonarqube/sonar-scanner.properties
> +  traffic_incident_parser, \
These are new packages that were added to develop, they're just showing here because i resolved some merge conflict

2021-02-08 18:25 UTC, kjrush commented on unobstructed_lanechange/src/unobstructed_lanechange.cpp
> +            first = true;
This is rather confusing using nested `first`s or resetting this variable every loop. Is there a more straightforward way to express this? If not, let's rename or add comments for clarity

2021-02-08 18:25 UTC, kjrush commented on unobstructed_lanechange/src/unobstructed_lanechange.cpp
> +    lanelet::BasicLineString2d  UnobstructedLaneChangePlugin::create_lanechange_route(lanelet::BasicPoint2d start, lanelet::ConstLanelet& start_lanelet, lanelet::BasicPoint2d end, lanelet::ConstLanel
Can we rename this to `create_lanechange_trajectory` or `create_lanechange_path`, since it doesn't actually create a route?

2021-02-09 13:22 UTC, kjrush commented
The only failure on Sonar seems to be the flagged security hotspot. I lack permissions to change the review status, but the use of PRNG that it flags isn't an issue in my assessment, so this should be good to merge.

2021-02-09 13:22 UTC, merged