Update environment.launch
usdot-fhwa-stol/carma-platform pull request #1049
Opened 2021-01-28 16:52 UTC by itabrl

# PR Details
## Description

set gpu flag to true
## Related Issue
894

## How Has This Been Tested?
deployed on White Pacifica 

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-01-28 16:54 UTC, aswath1 approved these changes

2021-01-29 14:14 UTC, msmcconnell requested changes
Just blocking Merge until we can hammer out the vm vs vehicle discussion

2021-02-04 16:48 UTC, msmcconnell requested changes
For this to work properly you need to be passing in this argument from the config, not hard coding it. Otherwise the VM will still try to use cuda

2021-02-05 15:05 UTC, msmcconnell requested changes

2021-02-05 15:23 UTC, msmcconnell approved these changes
Will merge when all 3 prs are complete

2021-02-05 16:10 UTC, merged