Feature/route lane change idl
usdot-fhwa-stol/carma-platform pull request #1324
Opened 2021-06-24 17:43 UTC by lewisid

# PR Details
## Description

As identified in CAR-2785: Create High Level Design for Basic TravelDONE, UI needs a simple topic to display what is the next lane change direction is (left/right) and how far it is until an upcoming lane change is required. This story is to develop this logic, which should leverage existing plugins to identify when the lane change will actually occur and to make this information available to the UI. It is understood that the lane change location cannot be known sooner than it is planned by the relevant plugin. Should be published as soon as it is known and updated as actual point of lane change approaches or shifts.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-06-24 19:04 UTC, msmcconnell commented
Per @snallamothu we will hold off on merging this change for zephyr and will target it to develop as we do not have time to verify before Friday and its not use case critical functionality.

2021-06-24 19:04 UTC, msmcconnell requested changes
Blocking till zephyr release per my earlier comment

2021-06-25 15:28 UTC, msmcconnell commented
@aswath1 @lewisid does this replace Ash's earlier PR https://github.com/usdot-fhwa-stol/carma-platform/pull/1300 ? If so lets close the other PR

2021-06-25 15:31 UTC, msmcconnell requested changes

2021-06-25 15:31 UTC, msmcconnell commented on carma/launch/guidance.launch
> +    <remap from="upcoming_lane_change_status" to="$(optenv CARMA_GUIDE_NS)/upcoming_lane_change_status"/>
I believe this remapping will not work. remappings are applied top-down within scope. The remappning is scoped to the group tag but there is nothing below it, so it has no impact on the system.

2021-06-28 15:42 UTC, msmcconnell requested changes

2021-06-28 20:03 UTC, MishkaMN commented
Closed this PR in favor of https://github.com/usdot-fhwa-stol/carma-platform/pull/1320

2021-06-28 20:03 UTC, closed without merging