add exception for no temp shortest path
usdot-fhwa-stol/carma-platform pull request #1333
Opened 2021-06-29 18:53 UTC by adev4a

# PR Details
This pr fixes Issue #1320 .
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

Unit Tested and Integration tested.

![image](https://user-images.githubusercontent.com/51463994/123851692-81b47900-d8e9-11eb-90ba-e557810f7b6d.png)

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-07-01 20:27 UTC, snallamothu approved these changes

2021-07-02 17:51 UTC, adev4a commented
Holding off on merge till CI build error is resolved

2021-07-22 18:11 UTC, msmcconnell requested changes

2021-07-22 18:11 UTC, msmcconnell commented on cooperative_lanechange/src/cooperative_lanechange.cpp
>          lanelet::routing::RoutingGraphUPtr map_graph = lanelet::routing::RoutingGraph::build(*(wm_->getMap()), *traffic_rules);
You should use wm.getMapRoutingGraph() here instead of building it yourself which is very time consuming

2021-07-30 19:49 UTC, merged