CARMA-WEB-UI: traffic signal intersection id and group id are not available
usdot-fhwa-stol/carma-platform pull request #1439
Opened 2021-09-17 04:43 UTC by aswath1

# PR Details
## Description
There is one traffic signal controller respectively at each side of the road to signalize the vehicle whether the vehicle should stop at the intersection or not. In another word, there are two traffic signal controllers in total for the workzone use case.

The traffic signal controllers are constantly sending signal to v2xhub. V2xhub forward the corresponding SPAT messages to the SV vehicle. However, vehicle OBU receives all the SPAT messages from both traffic signal controllers. The Platform and UI need to process/display the SPAT correctly and distinguish which SPAT is from the approaching traffic signal controller for the SV.

## Related Issue

https://github.com/usdot-fhwa-stol/carma-platform/issues/1420
## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-09-17 12:57 UTC, MishkaMN requested changes
overall looks good to me except typo. It includes some extra changes from develop for participant type I think. I saw release:a1 config/VehicleConfigParams still supports it, so it wouldn't be too bad to have them?

2021-09-17 12:57 UTC, MishkaMN commented on carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.h
> +   * \param middle_opposite_lanelets A lgetInterGroupIdsByLightRegIdk() connects to back diagonal (their directions are expected to be opposite of parallel ones)
extra comments here

2021-09-17 13:48 UTC, msmcconnell requested changes

2021-09-17 13:48 UTC, msmcconnell commented on carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.h
> +  std::string getVehicleParticipationType();
Looks like this still contains Isaiah's changes to develop from a few days ago

2021-09-17 20:08 UTC, msmcconnell approved these changes
LGTM. Please test before merging

2021-09-20 14:15 UTC, MishkaMN approved these changes

2021-09-21 15:50 UTC, MishkaMN commented
tested on fusion at TFHRC

2021-09-21 15:53 UTC, merged