Update baseline and recompiled cut_in_mid_rear
usdot-fhwa-stol/carma-platform pull request #1647
Opened 2022-03-03 00:54 UTC by xuhan417

# PR Details
## Description
This is UCLA team's commit of the IHP2 platoon plugin cut-in join from middle and rear.

## Related Issue
There is no related issues.

## Motivation and Context
This is the development for IHP2 project cut-in join from middle and rear.

PR context: 
- Mid/rear join functions.
- Include "join index" in STATUS params, and keep tracking it as a property of platoonmember class.
- Update plan type name and platoon manager APF function.

## How Has This Been Tested?
- Add unit test to test additional state transitions.
- Compile and ran on UCLA's vehicle platform (single vehicle only).

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-03-11 19:47 UTC, TonysCousin requested changes

2022-03-11 19:47 UTC, TonysCousin commented on platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
> +        // UCLA: read current request plan
Why is this here?  It isn't used anywhere.

2022-03-11 19:47 UTC, TonysCousin commented on platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
> +            //Note: remove join_index to STATUS param. request.join_index = -1;
Need to keep the previous code hre to add join_index to the status params.

2022-03-11 19:47 UTC, TonysCousin commented on platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
> +        //Note: remove join_index to STATUS param. request.join_index = target_join_index_;
Need the join_index as part of the params

2022-03-11 19:47 UTC, TonysCousin commented on platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
>          // UCLA: assign a new plan type
10 lines above here target_join_index is calculated by asking PlatoonManager about the index of platoon members. Problem is pm_ represents the hosts current platoon (as a solo vehicle), and not the platoon it desires to join.  So this info is meaningless.
I think what we need is for platoon_strategic_ihp to be able to look at INFO message from the neighbor platoon leader and from its leader DTD, size and length figure out the closest index.  As I have suspected for some time, the INFO message probably really needs to include something about each member (e.g. list of IDs in order); then a potential joiner can monitor the STATUS messages coming from each member to get their exact locations.  That would be a major change, so is worth discussing; we can probably come up with a better approach after some careful thought.

2022-03-11 19:47 UTC, TonysCousin commented on platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
> +    // UCLA: run prepare to depart state for depart from platoon
I suspect that there is no transition out of the PREPARETOJOIN state other than for exception situations.  I would expect to see it in the run_prepare_to_join() method and normally transition to FOLLOWER or CANDIDATEFOLLOWER.  Maybe I'm looking in the wrong place?

2022-03-17 22:56 UTC, xuhan417 commented on platooning_strategic_IHP/include/platoon_manager_ihp.h
> +        void updatesOrAddMemberInfo(std::string senderId, double cmdSpeed, double dtDistance, double ctDistance, double curSpeed, int joinIndex);
Switch join index to STATUS param.

2022-03-21 23:53 UTC, xuhan417 commented on platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
> +        bool isFinishLaneChangeMidorRear = plan_type.type == cav_msgs::PlanType::CUT_IN_MID_OR_REAR_DONE;
updated

2022-03-28 20:02 UTC, saina-ramyar requested changes
Some of my comments in this PR are from before, and they are already addressed or disusssed. You can ignore those. 
Also, I noticed these files: src/.vscde and src/reference_code.zip which seem to be auto-generated by vscde. These shouldn't be merged, so please delete them, and make sure such files don't get pushed to the PR.

2022-03-31 21:42 UTC, TonysCousin approved these changes

2022-04-06 04:03 UTC, saina-ramyar approved these changes

2022-04-12 18:57 UTC, saina-ramyar commented
Replaced by PR #1719 due to conflicts.

2022-04-12 18:57 UTC, closed without merging