Fix/equation x x2
usdot-fhwa-stol/carma-platform pull request #1711
Opened 2022-04-07 19:43 UTC by MishkaMN

# PR Details
## Description

Added ability to choose early or late arrival for case when the car starts from WAITING state. Then it should only go if late arrival in green is certain.
Trying to fix negative duration error by adding max(x,0) guard.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-07 20:12 UTC, msmcconnell requested changes

2022-04-07 20:12 UTC, msmcconnell commented on lci_strategic_plugin/src/lci_strategic_plugin.cpp
> +  auto bool_optional_late_certainty = canArriveAtGreenWithCertainty(current_state.stamp, traffic_light, true, false);
This should be below the valid light state check?

2022-04-07 20:12 UTC, msmcconnell commented on lci_strategic_plugin/src/lci_strategic_plugin.cpp
> +    throw std::invalid_argument("Unable to resolve the green signal...");
Instead of throwing an exception just return another stop and wait maneuver to keep the vehicle in place while the light rolls over.

2022-04-08 10:03 UTC, aswath1 approved these changes

2022-04-08 10:22 UTC, snallamothu approved these changes

2022-04-08 10:25 UTC, snallamothu approved these changes

2022-04-08 12:46 UTC, MishkaMN commented
created another duplicate PR here
https://github.com/usdot-fhwa-stol/carma-platform/pull/1713
and that one is merged earlier, so closing this

2022-04-08 12:46 UTC, closed without merging