Port traffic_incident_parser to ROS2
usdot-fhwa-stol/carma-platform pull request #1767
Opened 2022-05-13 17:16 UTC by JonSmet

# PR Details
## Description

This PR includes updates to port the traffic_incident_parser node to ROS2 and to launch it from the environment.launch.py launch file.

Additionally, this PR includes updates to several subscribers and publishers created within carma_wm_ros2 in order to support publishers being able to re-publish earlier messages to late-joining subscribers.

## Related Issue

Issue #1766 

## Motivation and Context

## How Has This Been Tested?

Nodes built and launched locally; unit test results match the results from ROS1 version.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-13 18:08 UTC, msmcconnell requested changes

2022-05-13 18:08 UTC, msmcconnell commented on carma_wm_ros2/src/WMListener.cpp
> +  map_update_options.use_intra_process_comm = rclcpp::IntraProcessSetting::Disable; // Disable intra-process comms for the map update subscriber
ditto on link explaining reason

2022-05-16 14:09 UTC, JonSmet commented on carma_wm_ros2/src/MapUpdateLoggerNode.cpp
> +    readable_pub_options.use_intra_process_comm = rclcpp::IntraProcessSetting::Disable; // Disable intra-process comms for the map update debug publisher
Added

2022-05-16 14:09 UTC, JonSmet commented on carma_wm_ros2/src/WMListener.cpp
> +  map_update_options.use_intra_process_comm = rclcpp::IntraProcessSetting::Disable; // Disable intra-process comms for the map update subscriber
Added

2022-05-16 14:28 UTC, msmcconnell approved these changes

2022-05-16 14:28 UTC, merged