Feature/stop and wait plugin ros2
usdot-fhwa-stol/carma-platform pull request #1853
Opened 2022-07-15 22:32 UTC by aswath1

# PR Details
## Description

stop and wait plugin ros2
## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-07-18 16:24 UTC, MishkaMN commented on stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
> +  RCLCPP_INFO_STREAM(nh_->get_logger(),"planning state x:" << req->vehicle_state.x_pos_global << ", y: " << req->vehicle_state.y_pos_global << ", speed: " << req->vehicle_state.longitudinal_vel);
Please have the logging level same. Ditto for all other logging statements

2022-07-18 16:24 UTC, MishkaMN commented on stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
> +    RCLCPP_INFO_STREAM(nh_->get_logger(),"Detected that car is already stopped! Ignoring the request to plan Stop&Wait");
remove this line with DEBUG, it is redundant

2022-07-18 16:28 UTC, MishkaMN commented on stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
> +  while (rclcpp::Time(traj.back().target_time) - rclcpp::Time(traj.front().target_time) < rclcpp::Duration(config_.minimal_trajectory_duration))
`config_.minimal_trajectory_duration` is `double` so rclcpp::Duration(double) is in nanoseconds. So it needs to be `config_.minimal_trajectory_duration * 1e9`

2022-07-18 16:30 UTC, MishkaMN commented on stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
> +    new_point.target_time = rclcpp::Time(new_point.target_time) + rclcpp::Duration(config_.stop_timestep);
`config_.stop_timestep` is `double` so rclcpp::Duration(double) is in nanoseconds. So it needs to be config_.stop_timestep * 1e9`

Good rule of thumb to check these kind of error is to search your packages folder using your VSCode search every instances of `Duration(` or `Time(` (pay attention to the parenthesis). OR also instances of `rclcpp::Duration ` or `rclcpp::Time ` (also pay attention to the space). And once you found it, edit with `1e9` or other constructors as you see fit.

2022-07-18 16:32 UTC, MishkaMN commented on stop_and_wait_plugin/src/stop_and_wait_plugin_node.cpp
> +    config_.cernterline_sampling_spacing = declare_parameter<std::string>("cernterline_sampling_spacing", config_.cernterline_sampling_spacing);
let's fix this typo while we are at it
`centerline_sampling_spacing`
Please fix it in .hpp and yaml file as well

2022-07-18 16:33 UTC, MishkaMN commented on stop_and_wait_plugin/test/test_stopandwait_plugin.cpp
> +#include "stop_and_wait_plugin.hpp"
remove redundancy

2022-07-18 16:34 UTC, MishkaMN commented on carma/launch/guidance.launch.py
> +        get_package_share_directory('stop_and_wait_plugin'), 'config/stop_and_wait_plugin_params.yaml')
Please refer to the route_and_following_plugin's comment on where to call this. remove from here.

2022-07-18 18:24 UTC, aswath1 commented
https://github.com/usdot-fhwa-stol/carma-platform/issues/1857

2022-07-19 05:15 UTC, MishkaMN requested changes

2022-07-19 05:15 UTC, MishkaMN commented on stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
> +  RCLCPP_INFO_STREAM(nh_->get_logger(),"Starting stop&wait planning");
log statements need to change. it applies to all log statements

2022-07-19 05:15 UTC, MishkaMN commented on stop_and_wait_plugin/test/test_stopandwait_plugin.cpp
> -}
Please include ROS 2 version of unit test main. Any other ros2 package will have it like plan_delegator, ILC etc

2022-07-21 15:29 UTC, MishkaMN approved these changes

2022-07-21 15:36 UTC, MishkaMN requested changes

2022-07-21 15:36 UTC, MishkaMN commented on stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
> +  RCLCPP_INFO_STREAM(nh_->get_logger(),"Starting stop&wait planning");
log levels have to stay the same

2022-07-21 15:38 UTC, MishkaMN commented
please try to fix code smells while you are at it

2022-07-25 16:12 UTC, MishkaMN approved these changes

2022-07-25 16:13 UTC, merged