Feature/uc3
usdot-fhwa-stol/carma-platform pull request #1919
Opened 2022-08-29 15:52 UTC by MishkaMN

# PR Details
## Description
TODO

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-09-29 13:24 UTC, msmcconnell requested changes
There's a lot of near term TODOs here. We need to track these. Please open a github issue that describes where they all are so they can be fixed.

2022-09-29 13:24 UTC, msmcconnell commented on carma_wm/test/CARMAWorldModelTest.cpp
> +TEST(CARMAWorldModelTest, DISABLED_getTrafficSignalId)
Why are these unit tests disabled?

2022-09-29 13:24 UTC, msmcconnell commented on light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin.cpp
> +            RCLCPP_DEBUG_STREAM(logger_->get_logger(), "Given vehicle position is not on the road! Returning...");
Why debug not error?

2022-09-30 06:09 UTC, MishkaMN commented on carma_wm/test/CARMAWorldModelTest.cpp
> +TEST(CARMAWorldModelTest, DISABLED_getTrafficSignalId)
accidentally pushed before enabling back

2022-09-30 06:09 UTC, MishkaMN commented on light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin.cpp
> +            RCLCPP_DEBUG_STREAM(logger_->get_logger(), "Given vehicle position is not on the road! Returning...");
made it back to error

2022-10-03 14:57 UTC, msmcconnell approved these changes

2022-10-03 15:25 UTC, merged