enable and disable opening tunnels
usdot-fhwa-stol/carma-platform pull request #1998
Opened 2022-12-22 14:52 UTC by saina-ramyar

# PR Details
## Description

Opening HTTP tunnels to CARMA Cloud can be enabled and disabled using a Flag in CARMA Config

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-12-22 15:01 UTC, msmcconnell requested changes

2022-12-22 15:01 UTC, msmcconnell commented on carma/launch/message.launch.py
> +    enable_opening_tunnels = rospy.get_param("/enable_opening_tunnels", False)
This won't work. For one it's a ros1 parameter call not ros2 and second, I don't think there's a guarantee of the parameter being set during file processing. I think the most reliable option would be to pass the argument down the launch chain. 
carma_docker -> carma_src -> message.launch.py

2022-12-22 17:04 UTC, msmcconnell requested changes

2022-12-22 17:04 UTC, msmcconnell commented on carma/launch/message.launch.py
> +    if enable_opening_tunnels:
I also think you probably need to use one of the launch substitutions to evaluate the variable 
https://answers.ros.org/question/382167/is-it-possible-to-have-a-conditional-in-a-launch-file-using-declarelaunchargument/

2023-01-03 14:34 UTC, dan-du-car approved these changes

2023-01-03 14:59 UTC, msmcconnell approved these changes

2023-01-03 15:00 UTC, merged