final_dev
usdot-fhwa-stol/carma-platform pull request #2083
Opened 2023-04-09 19:56 UTC by aswath1

# PR Details
## Description
The detailed design for Stop and Dwell Strategic Plugin was created as part ofTT-15: Create detailed design for Stop Controlled Dwell Time Strategic Plugin
DONE
 . The goal of this story is to do development and add necessary unit test based on the detailed design document, and publish the code to the GitHub.
Then second implementation story could be for generating the maneuver plan in the plan_maneuvers_callback() function.

## Related Issue
https://github.com/usdot-fhwa-stol/carma-platform/issues/2072
https://github.com/usdot-fhwa-stol/carma-platform/issues/2071

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-04-11 13:24 UTC, MishkaMN requested changes
Overall looks good. Need to add it to the carma/plugins.launch.py

2023-04-17 13:17 UTC, MishkaMN commented on carma/launch/plugins.launch.py
> +                    ("current_pose", [ EnvironmentVariable('CARMA_LOCZ_NS', default_value=''), "/current_pose" ] ),
Add `("state", [ EnvironmentVariable('CARMA_GUIDE_NS', default_value=''), "/state" ] ),`

2023-04-18 03:39 UTC, MishkaMN commented
Looks good to me.

2023-04-18 03:39 UTC, merged

2024-04-02 00:55 UTC, maefromm commented
@MishkaMN  can the 2 issues above be closed now?

2024-04-02 03:00 UTC, MishkaMN commented
> @MishkaMN  can the 2 issues above be closed now? 

@maefromm yes. They can be closed now