Port driver manager to ros2 subsystem controller
usdot-fhwa-stol/carma-platform pull request #2134
Opened 2023-08-21 12:34 UTC by adev4a

# PR Details
This PR ports the health monitor's driver functionality to ros2. This port is currently being made to support both ros1 and ros2 drivers. 

## Description
The logic implemented in the driver_subsystem_controller follows the same logic as the ros1 manager, in that it loads the required driver names from carma-config. The ros2 drivers are then managed by the driver_subsystem_controller.
The driver node names specified in carma-config are used define which drivers will be treated as required. 
In order to manage ros1 drivers, updates on driver readiness and errors will still be published on system alert.
System alert will track changes from the required ros2 drivers as well.

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-24 15:21 UTC, JonSmet requested changes

2023-08-24 15:47 UTC, adev4a commented on subsystem_controllers/src/drivers_controller/drivers_controller_node.cpp
> +    long start_duration = sd.nanoseconds()/1e6;
They're being used to define start_duration which is passed to the driver_manager

2023-08-24 15:49 UTC, adev4a commented on subsystem_controllers/include/subsystem_controllers/drivers_controller/driver_manager.hpp
> +        std::string are_critical_drivers_operational_car(long current_time);
Yes, good point

2023-08-25 14:03 UTC, adev4a commented on subsystem_controllers/src/drivers_controller/drivers_controller_node.cpp
> +    long start_duration = sd.nanoseconds()/1e6;
Updated, start duration is now being used to create the driver_manager

2023-08-25 17:03 UTC, JonSmet requested changes

2023-09-06 14:46 UTC, JonSmet requested changes

2023-09-06 14:46 UTC, JonSmet commented on subsystem_controllers/config/drivers_controller_config.yaml
> +    # Double: The time allocated for system startup in seconds
Let's change this param type to `Integer`

2023-09-06 14:46 UTC, JonSmet commented on subsystem_controllers/include/subsystem_controllers/drivers_controller/driver_manager.hpp
> +         * \brief Default constructor for DriverManager with driver_timeout_ = 1000
Let's add units to this comment for the driver_timeout_ setting

2023-09-06 15:03 UTC, JonSmet submitted a review, later dismissed

2023-09-11 12:56 UTC, JonSmet approved these changes

2023-09-11 12:56 UTC, merged