<wip> lci_strategic_plugin hangs when trying to find entry on green signal
usdot-fhwa-stol/carma-platform pull request #2228
Opened 2023-12-17 16:24 UTC by MishkaMN

# PR Details
## Description
TODO:
Currently the lci_strategic_plugin is expecting fixed signal SPAT where the timing can be extrapolated indefinitely. 
However, the way signal is being processed at the moment in CDA-Research VRU use case is that it is not necessarily detecting the fixed signal and just accepting states broadcasted at the moment.
Fix 1: Detect fixed signal and extrapolate
Fix 2: If not suitable green entry is found just plan for cruising and stopping until suitable green entry time is broadcasted

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-12-19 15:45 UTC, adamlm submitted a review, later dismissed

2023-12-20 16:50 UTC, adamlm requested changes

2023-12-20 16:50 UTC, adamlm commented on lci_strategic_plugin/include/lci_strategic_plugin/lci_strategic_plugin.hpp
> +  std::tuple<rclcpp::Time, bool> get_nearest_valid_entry_time(const rclcpp::Time& current_time, const rclcpp::Time& earliest_entry_time, lanelet::CarmaTrafficSignalPtr signal, double minimum_required
Consider changing this to `std::optional<rclcpp::Time>` to indicate that a nearest valid entry time does not exist under the given function arguments.

2023-12-20 16:50 UTC, adamlm commented on lci_strategic_plugin/src/lci_strategic_plugin_algo.cpp
> +rclcpp::Time get_eet_or_tbd(const rclcpp::Time& earliest_entry_time, const lanelet::CarmaTrafficSignalPtr& signal)
See comment about `std::optional`.

2023-12-20 16:50 UTC, adamlm commented on lci_strategic_plugin/src/lci_strategic_plugin_algo.cpp
> +    std::tie(nearest_green_entry_time, in_tbd) = get_nearest_valid_entry_time(current_state.stamp, earliest_entry_time, traffic_light);
See comment about `std::optional`.

2023-12-21 13:55 UTC, adamlm approved these changes

2023-12-22 18:38 UTC, MishkaMN commented
This was tested locally to be able to build. The autoware.ai's carma-develop branch is pushing to wrong hub.docker.com image tag (carma-develop instead of develop) which is why the CI is failing. Therefore force merging this and force pushing to `usdotfhwastoldev/autoware.ai:develop` with the updated image until the automated process is fixed

2023-12-22 18:38 UTC, merged