fix disengage
usdot-fhwa-stol/carma-platform pull request #2276
Opened 2024-01-11 18:47 UTC by MishkaMN

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-01-11 19:50 UTC, JonSmet requested changes

2024-01-11 19:50 UTC, JonSmet commented on carma_guidance_plugins/include/carma_guidance_plugins/control_plugin.hpp
> +    void guidance_state_callback(carma_planning_msgs::msg::GuidanceState::UniquePtr plan);
Can we change `plan` here to `msg`?

2024-01-11 20:08 UTC, MishkaMN commented on carma_guidance_plugins/include/carma_guidance_plugins/control_plugin.hpp
> +    void guidance_state_callback(carma_planning_msgs::msg::GuidanceState::UniquePtr plan);
renamed

2024-01-11 20:14 UTC, MishkaMN commented
Please hold off on merging

2024-01-16 14:58 UTC, MishkaMN commented
Closing this PR due to prioritization. Created an issue related to it and will pick up later if time allows

2024-01-16 14:58 UTC, closed without merging