Update rosbag2 recording format to mcap
usdot-fhwa-stol/carma-platform pull request #2285
Opened 2024-01-18 16:20 UTC by adev4a

# PR Details
This PR updates the storage format for rosbag2 to mcap.
mcap rosbag2 files are recorded with message definitions of the recorded messages, making it possible to read the rosbag in an environment where the messages have not been built. 
Further the mcap format is directly usable with the rosbag2 python API to parse messages without defining custom messages again and is also supported by analysis tools like Foxglove.

## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?
Locally integration Tested

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-01-18 19:20 UTC, adev4a commented
https://github.com/usdot-fhwa-stol/carma-base/pull/184 needs to be merged first to ensure the docker images are built correctly

2024-01-19 16:52 UTC, JonSmet requested changes

2024-01-19 16:52 UTC, JonSmet commented on carma/launch/ros2_rosbag.launch.py
> +        description = "Path to file contain vehicle configuration parameters"
Just a minor copy+paste error, let's update `description` here.

2024-01-23 18:42 UTC, JonSmet approved these changes

2024-01-23 21:53 UTC, JonSmet commented
Holding off on merging this until the usdotfhwastoldev/autoware.ai:develop [Docker Hub image](https://hub.docker.com/r/usdotfhwastoldev/autoware.ai/tags) is updated (due to the related [carma-base PR](https://github.com/usdot-fhwa-stol/carma-base/pull/184)).

2024-01-24 21:38 UTC, merged