Sync develop to master
usdot-fhwa-stol/carma-platform pull request #2371
Opened 2024-04-24 20:54 UTC by paulbourelly999

# PR Details
## Description
Merge PR to formalize release of master into develop as part of CARMA release process for 4.5.0. 

PR created automatically via CARMA release tool and Github CLI
## Motivation and Context

This PR brings the tested and reviewed contents of the master release/candidate into develop for final release preparation

## How Has This Been Tested?

This release branch (minus final version number changes) has been tested through the CARMA verification test plan.

## Checklist:
- [X] I have added any new packages to the sonar-scanner.properties file
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2024-04-24 21:02 UTC, MishkaMN requested changes

2024-04-24 21:02 UTC, MishkaMN commented on docker/checkout.bash
> +# NOTE: Additional information regarding the rosbag2 improvements on this branch are included in the forked repository's README.
let's move the rosbag description above the clone command of rosbag2

2024-04-24 21:15 UTC, MishkaMN submitted a review, later dismissed

2024-04-24 22:42 UTC, MishkaMN approved these changes

2024-04-25 15:00 UTC, kjrush commented on Dockerfile
> +ARG GIT_BRANCH="develop"
Now I'm less sure about my comment regarding ENV on the other PR, if this works I'm not clear on why the other one seems to return empty string when eval'ing ${GIT_BRANCH} in checkout.bash. Hmm.

2024-04-25 15:02 UTC, kjrush approved these changes

2024-04-29 14:32 UTC, merged