add permissive movement to allowed
usdot-fhwa-stol/carma-platform pull request #2373
Opened 2024-04-30 20:28 UTC by adev4a

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-05-06 14:18 UTC, MishkaMN requested changes

2024-05-06 14:18 UTC, MishkaMN commented on lci_strategic_plugin/src/lci_strategic_plugin.cpp
> +      || (early_arrival_state_by_algo_optional.get().second == lanelet::CarmaTrafficSignalState::PERMISSIVE_MOVEMENT_ALLOWED));
All of the OR or AND conditions added in this PR can be made concise by using helper function called 
`isAllowedMovement`  where 
```
bool isAllowedMovement(const lanelet::CarmaTrafficSignalState& state) {
    return state == lanelet::CarmaTrafficSignalState::PROTECTED_MOVEMENT_ALLOWED ||
           state == lanelet::CarmaTrafficSignalState::PERMISSIVE_MOVEMENT_ALLOWED;
}
```

2024-05-09 22:55 UTC, adev4a commented on lci_strategic_plugin/src/lci_strategic_plugin_algo.cpp
> +        if(traffic_light->signal_durations[lanelet::CarmaTrafficSignalState::PROTECTED_MOVEMENT_ALLOWED]){
Thats a nice suggestion

2024-05-09 22:55 UTC, adev4a commented on lci_strategic_plugin/src/lci_strategic_plugin_algo.cpp
> +        if(traffic_light->signal_durations[lanelet::CarmaTrafficSignalState::PROTECTED_MOVEMENT_ALLOWED]){
Just updated it

2024-05-14 08:15 UTC, MishkaMN requested changes

2024-05-14 08:15 UTC, MishkaMN commented on lci_strategic_plugin/src/lci_strategic_plugin_algo.cpp
> +int LCIStrategicPlugin::getClearanceDuration(lanelet::CarmaTrafficSignalPtr traffic_light)
The name is little misleading as it is getting movement allowed durations not clearance

2024-11-18 19:04 UTC, MishkaMN commented
@adev4a is this PR still needed?

2024-11-19 16:48 UTC, adev4a commented
Yes,  this PR wasn't merged since it hasn't been integration tested. But since we have no integration testing planned for this plugin currently, lets merge it and test when work begins on this plugin again.

2024-11-19 17:14 UTC, MishkaMN submitted a review, later dismissed

2024-11-20 18:05 UTC, MishkaMN requested changes

2024-11-20 18:05 UTC, MishkaMN commented on lci_strategic_plugin/src/lci_strategic_plugin.cpp
> +    return state == lanelet::CarmaTrafficSignalState::PROTECTED_MOVEMENT_ALLOWED |
aren't we supposed to use || operator?

2024-11-20 19:10 UTC, MishkaMN approved these changes

2024-11-20 20:23 UTC, merged